- name: Create protected Volume
  hosts: localhost
  gather_facts: false
  vars:
      https:          true
      validate_certs: false
      use_rest:       "Always"

  tasks:
  - name: load vars
    include_vars:
      dir: ../vars

  - name: Create volume on primary SVM
    na_ontap_volume:
      hostname:              "{{ PRI_CLU }}"
      username:              "{{ PRI_CLU_USER }}"
      password:              "{{ PRI_CLU_PASS }}"
      state:                 present
      name:                  testvol14
      vserver:               "{{ PRI_SVM }}"
      size:                  100
      size_unit:             gb
      aggregate_name:        "{{ PRI_AGGR }}"
      comment:               Created with Ansible
      space_guarantee:       volume
      policy:                default
      junction_path:         "/{{ PRI_SVM }}_nfs_01"
      volume_security_style: unix
